import { z } from 'zod';

/**
 * Review labels schema
 * NLP-derived labels for reviews (sentiment, topics, etc.)
 * Generated by background jobs
 */
export const ReviewLabelSchema = z.object({
  id: z.string().uuid(),
  review_id: z.string().uuid(),
  label_type: z.enum(['sentiment', 'topic', 'professionalism', 'authenticity']),
  label_value: z.string().min(1).max(100),
  confidence: z.number().min(0).max(1),
  created_at: z.string().datetime(),
});

export type ReviewLabel = z.infer<typeof ReviewLabelSchema>;

export const CreateReviewLabelSchema = ReviewLabelSchema.omit({
  id: true,
  created_at: true,
});

export type CreateReviewLabel = z.infer<typeof CreateReviewLabelSchema>;
